### ISSUE TITLE
about the local_variables_initializer

### ISSUE THREAD

**Issue by irfanICMLL** [holyseven/PSPNet-TF-Reproduce#7]
Sorry it is me again!
I wonder what is the local variables in this tf graph? Why we need to initialize the local variables after we save the snapshot? I find that the iou will change dramatically every time we save the snapshot.

Is that because the printed iou, which represents for a mean iou for several steps, and the counter will be cleared zero   after the local initialize?
Or we train some new parameters every time we save the model?

if step % snapshot == 0:
            saver.save(sess, logdir.snapshot_dir + '/model.ckpt', global_step=step)
            sess.run([tf.local_variables_initializer()])

Thank you for your kind help.

**Comment by holyseven** [comment]
> Is that because the printed iou, which represents for a mean iou for several steps, and the counter will be cleared zero after the local initialize?

Yes. Local variable is just a confusion matrix which accumulates each iteration. After the initializer of local variables, the confusion matrix will be zero.

> Or we train some new parameters every time we save the model?

No.

Computing mean IoU scores for **one** image does not seem reasonable because not all classes will be  present in this image. So I choose to accumulate the confusion matrix for a specific number of iterations which happens to be equal to the one for saving a snapshot. And of course, you can set it to other value.
